### ISSUE TITLE
npm install take infinite time to load .

### ISSUE THREAD

**Issue by jeetendra18** [cmacdonnacha/angular-material-boilerplate#2]
I think the issue with loading material-design-icons

![image](https://cloud.githubusercontent.com/assets/5902385/23260262/f4f61170-f9f6-11e6-9980-4c6d256a1d3a.png)

**Comment by cmacdonnacha** [comment]
Hey,

I just tested this with a new clean install and it worked fine. What version of nodejs and npm are you using?

You can find this by typing `node --version` and `npm --version`

**Comment by jeetendra18** [comment]
node : V6.6.0
npm : 3.10.3

the installation progressed , may be due to slow internet it took time. but end with following errors

"297573 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
297574 error node v6.6.0
297575 error npm  v3.10.3
297576 error code ELIFECYCLE
297577 error phantomjs-prebuilt@2.1.14 install: `node install.js`
297577 error Exit status 1
297578 error Failed at the phantomjs-prebuilt@2.1.14 install script 'node install.js'.
297578 error Make sure you have the latest version of node.js and npm installed.
297578 error If you do, this is most likely a problem with the phantomjs-prebuilt package,
297578 error not with npm itself."







![image](https://cloud.githubusercontent.com/assets/5902385/23261760/d710aa6a-f9fd-11e6-8784-d9c4210b407b.png)


Thanks

**Comment by cmacdonnacha** [comment]
Try running `npm install` again

Try updating nodejs and npm if that doesn't work.

**Comment by jeetendra18** [comment]
Thanks for your reply.

npm install works fine 

now issue with npm start

![image](https://cloud.githubusercontent.com/assets/5902385/23262217/fd2bd60a-f9ff-11e6-9a12-b0e85f9b291c.png)

**Comment by cmacdonnacha** [comment]
Looks like `gulp-sass` didn't install correctly. Try running `npm install gulp-sass` and try again.

**Comment by jeetendra18** [comment]
It was due to npm-saas, I reinstall it and all working fine.

Thanks for your support

**Comment by cmacdonnacha** [comment]
Good stuff. Hope you enjoy using the boilerplate. I would recommend that you still update to the latest version of NodeJs and npm. They've made a lot of fixes around permissions which may be why this didn't work for you the first time around.
